import uuid
import json
from flask import Blueprint, request, jsonify
from werkzeug.utils import secure_filename
import os, uuid
from .auth import login_required
from ..database import get_db

bp = Blueprint('notes', __name__, url_prefix='/student/notes')

@bp.route('/topic/<material_id>', methods=['GET', 'POST'])
@login_required
def note_by_topic(material_id):
    uid = request.user.get('uid')
    db = get_db()
    
    # Hotfix: Ensure schema columns exist
    try:
        db.execute("ALTER TABLE notes ADD COLUMN material_id TEXT")
        db.commit()
    except Exception:
        pass
    try:
        db.execute("ALTER TABLE notes ADD COLUMN file_url TEXT")
        db.commit()
    except Exception:
        pass
    try:
        db.execute("ALTER TABLE notes ADD COLUMN classroom_id TEXT")
        db.commit()
    except Exception:
        pass
        
    if request.method == 'GET':
        r = db.execute('SELECT * FROM notes WHERE student_id = ? AND material_id = ?', (uid, material_id)).fetchone()
        if not r:
            return jsonify({'note': None}), 200
        d = dict(r)
        d['flashcards'] = json.loads(d['flashcards_json']) if d['flashcards_json'] else []
        del d['flashcards_json']
        return jsonify({'note': d}), 200
        
    if request.method == 'POST':
        data = request.json
        classroom_id = data.get('classroom_id')
        original_text = data.get('original_text', '')
        file_url = data.get('file_url')
        
        existing = db.execute('SELECT id FROM notes WHERE student_id = ? AND material_id = ?', (uid, material_id)).fetchone()
        
        if existing:
            # Update
            nid = existing['id']
            db.execute('''
                UPDATE notes 
                SET original_text = ?, classroom_id = COALESCE(classroom_id, ?), file_url = COALESCE(?, file_url)
                WHERE id = ?
            ''', (original_text, classroom_id, file_url, nid))
        else:
            nid = str(uuid.uuid4())
            title = data.get('title', 'Topic Note')
            db.execute('''
                INSERT INTO notes (id, student_id, classroom_id, material_id, title, original_text, file_url)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            ''', (nid, uid, classroom_id, material_id, title, original_text, file_url))
            
        db.commit()
        return jsonify({'message': 'Note auto-saved', 'id': nid}), 200

@bp.route('/<note_id>/refine', methods=['POST'])
@login_required
def save_refinement(note_id):
    uid = request.user.get('uid')
    db = get_db()
    data = request.json
    
    # We expect `refined_summary` and `flashcards` to be passed here, generated by `/ai/notes/refine`
    refined_summary = data.get('refined_summary', '')
    flashcards = json.dumps(data.get('flashcards', []))
    
    # We update the note
    db.execute('''
        UPDATE notes
        SET refined_summary = ?, flashcards_json = ?
        WHERE id = ? AND student_id = ?
    ''', (refined_summary, flashcards, note_id, uid))
    
    db.commit()
    return jsonify({'message': 'Refined successfully'}), 200

@bp.route('/upload', methods=['POST'])
@login_required
def upload_note_file():
    if 'file' not in request.files:
        return jsonify({'error': 'No file provided'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    UPLOAD_FOLDER = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '..', 'uploads')
    os.makedirs(UPLOAD_FOLDER, exist_ok=True)
    
    ext = file.filename.rsplit('.', 1)[1].lower() if '.' in file.filename else 'bin'
    unique_name = f"note_{uuid.uuid4()}.{ext}"
    save_path = os.path.join(UPLOAD_FOLDER, unique_name)
    file.save(save_path)

    file_url = f"/uploads/{unique_name}"
    return jsonify({'file_url': file_url}), 201

@bp.route('/friends/<material_id>', methods=['GET'])
@login_required
def friends_notes_by_topic(material_id):
    uid = request.user.get('uid')
    db = get_db()
    
    # Get accepted friends that have a note on this material_id
    rows = db.execute('''
        SELECT n.id, n.title, n.original_text, n.refined_summary, n.flashcards_json, n.file_url, n.created_at, u.name as author_name
        FROM friends f
        JOIN users u ON (f.user1_id = u.id OR f.user2_id = u.id)
        JOIN notes n ON n.student_id = u.id
        WHERE (f.user1_id = ? OR f.user2_id = ?) 
          AND u.id != ? 
          AND f.status = 'accepted'
          AND n.material_id = ?
    ''', (uid, uid, uid, material_id)).fetchall()
    
    friends_notes = []
    for r in rows:
        d = dict(r)
        d['flashcards'] = json.loads(d['flashcards_json']) if d['flashcards_json'] else []
        del d['flashcards_json']
        friends_notes.append(d)
        
    return jsonify({'friends_notes': friends_notes}), 200

# Keep legacy methods just in case LearningDashboard still references them before frontend update
@bp.route('', methods=['GET', 'POST'])
@login_required
def manage_notes():
    uid = request.user.get('uid')
    db = get_db()
    
    if request.method == 'GET':
        rows = db.execute('SELECT * FROM notes WHERE student_id = ? ORDER BY created_at DESC', (uid,)).fetchall()
        notes = []
        for r in rows:
            d = dict(r)
            d['flashcards'] = json.loads(d['flashcards_json']) if d['flashcards_json'] else []
            del d['flashcards_json']
            notes.append(d)
        return jsonify({'notes': notes}), 200
        
    if request.method == 'POST':
        data = request.json
        nid = str(uuid.uuid4())
        db.execute('''
            INSERT INTO notes (id, student_id, classroom_id, title, original_text, refined_summary, flashcards_json)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (
            nid, uid, 
            data.get('classroom_id'),
            data.get('title', 'Untitled Refined Note'), 
            data.get('original_text', ''),
            data.get('refined_summary', ''),
            json.dumps(data.get('flashcards', []))
        ))
        db.commit()
        return jsonify({'message': 'Note saved', 'id': nid}), 201

@bp.route('/<note_id>', methods=['DELETE'])
@login_required
def delete_note(note_id):
    db = get_db()
    db.execute('DELETE FROM notes WHERE id = ?', (note_id,))
    db.commit()
    return jsonify({'message': 'Deleted successfully'}), 200
